name: dwm_example
description: Demonstrates how to use the dwm plugin.
publish_to: "none"

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  dwm:
    # When depending on this package from a real application you should use:
    #   dwm: ^x.y.z
    # See https://dart.dev/tools/pub/dependencies#version-constraints
    # The example app is bundled with the plugin so we use a path dependency on
    # the parent directory to use the current plugin's version.
    path: ../

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true
