name: dwm
description: Desktop Window Manager plugin that allows you accessing the operating system APIs.
version: 0.0.0-dev.2
repository: https://github.com/VadimMalykhin/dwm.flutter

environment:
  sdk: ">=2.17.5 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.1.2

dev_dependencies:
  flutter_lints: ^2.0.1

flutter:
  plugin:
    platforms:
      windows:
        pluginClass: DwmPluginCApi
